wandb_version: 1

seed:
  desc: null
  value: 0
dataset_name:
  desc: null
  value: ms
do_train:
  desc: null
  value: true
load_model:
  desc: null
  value: ../save/scGPT_human
mask_ratio:
  desc: null
  value: 0.0
epochs:
  desc: null
  value: 10
n_bins:
  desc: null
  value: 51
MVC:
  desc: null
  value: false
ecs_thres:
  desc: null
  value: 0.0
dab_weight:
  desc: null
  value: 0.0
lr:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 32
layer_size:
  desc: null
  value: 128
nlayers:
  desc: null
  value: 4
nhead:
  desc: null
  value: 4
dropout:
  desc: null
  value: 0.2
schedule_ratio:
  desc: null
  value: 0.9
save_eval_interval:
  desc: null
  value: 5
fast_transformer:
  desc: null
  value: true
pre_norm:
  desc: null
  value: false
amp:
  desc: null
  value: true
include_zero_gene:
  desc: null
  value: false
freeze:
  desc: null
  value: false
DSBN:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.33.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1741988232.0
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 12
      - 40
      - 45
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 11
      - 12
      - 40
      - 45
      - 49
      - 51
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.11
      5: 0.16.4
      6: 4.33.2
      8:
      - 1
      - 6
      13: linux-x86_64
